spring:
  datasource:
    url: jdbc:postgresql://$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
    username: $DATABASE_USERNAME
    password: $DATABASE_PASSWORD
    driver-class-name: org.postgresql.Driver
  session:
    jdbc:
      initialize-schema: always
  jpa:
    defer-datasource-initialization: on
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: 50e3a266646fe1
    password: f24fd78edff307
    port: 2525
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration