spring:
  datasource:
    url: jdbc:postgresql://$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
    username: $DATABASE_USERNAME
    password: $DATABASE_PASSWORD
    driver-class-name: org.postgresql.Driver
  session:
    jdbc:
      initialize-schema: never
  sql:
    init:
      encoding: UTF-8
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

ppij-id:
  security:
    lockoff:
      limit: 5
      cooldown: 300
    encryption:
      pgp:
        secret-key: PGP_SECRET_KEY