spring:
  datasource:
    url: jdbc:postgresql://$DATABASE_HOST:$DATABASE_PORT/$DATABASE_NAME
    username: $DATABASE_USERNAME
    password: $DATABASE_PASSWORD
    driver-class-name: org.postgresql.Driver
  session:
    jdbc:
      initialize-schema: always
  jpa:
    defer-datasource-initialization: on
  mail:
    default-encoding: UTF-8
    host:
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false