spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: user12
    password: s$cret
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    jdbc:
      initialize-schema: always
  jpa:
    defer-datasource-initialization: on